# Motion planning request to pass to planner
MotionPlanRequest request

---
# An error code reflecting what went wrong
MoveItErrorCodes error_code

ContactInformation[] contacts
---
# The internal state that the move arm action currently is in
string state

# Time to completion - this is a combination of requested planning time and trajectory completion time
duration time_to_completion
