coverage:
  precision: 2
  round: up
  range: "45...70"
  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        target: auto
        threshold: 5%
        informational: true
