# Turn on/off jogging along these dimensions.
# Give 'true' to enable jogging in the direction, 'false' to disable
bool control_x_translation
bool control_y_translation
bool control_z_translation
bool control_x_rotation
bool control_y_rotation
bool control_z_rotation
---
bool success