jog_arm_server:
  gazebo: true # Whether the robot is started in a Gazebo simulation environment
  collision_check: false # Check collisions?
  command_in_topic:  jog_arm_server/delta_jog_cmds
  command_frame:  base_link  # TF frame that incoming cmds are given in
  incoming_command_timeout:  5  # Stop jogging if X seconds elapse without a new cmd
  joint_topic:  joint_states
  move_group_name:  arm  # Often 'manipulator' or 'arm'
  singularity_threshold:  15  # Slow down when the condition number hits this (close to singularity)
  hard_stop_singularity_threshold: 20 # Stop when the condition number hits this
  command_out_topic:  sia5_controller/command
  planning_frame:  base_link  # Often 'base_link'
  low_pass_filter_coeff:  2.  # Larger --> trust the filtered data more, trust the measurements less.
  publish_period:  0.01  # 1/Nominal publish rate [seconds]
  scale:
    linear:  0.0004  # Max linear velocity. Meters per publish_period. Units is [m/s]
    rotational:  0.0008  # Max angular velocity. Rads per publish_period. Units is [rad/s]
  # Publish boolean warnings to this topic
  warning_topic:  jog_arm_server/warning