FILENAME = ompl-1256.tar.gz
TARBALL = build/$(FILENAME)
TARBALL_URL = https://code.ros.org/svn/release/download/thirdparty/ompl/$(FILENAME)
TARBALL_PATCH = console.patch

SOURCE_DIR = build/ompl_arch
UNPACK_CMD = tar xzf
MD5SUM_FILE = $(FILENAME).md5sum
