# The information for the plane that has been detected
Table table

# The raw clusters detected in the scan 
sensor_msgs/PointCloud[] clusters

# How many models should be returned for each recognition
int32 num_models

# Whether to perform a merge step based on model fit results
bool perform_fit_merge

---

# The list of models that have been detected along with confidence levels
moveit_manipulation_msgs/DatabaseModelPoseList[] models

# For each cluster, the index of the list of models that was fit to that cluster
# keep in mind that multiple raw clusters can correspond to a single fit
int32[] cluster_model_indices
