both_arms_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints:
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    - r_forearm_roll_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_upper_arm_roll_joint
    - l_elbow_flex_joint
    - l_forearm_roll_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
  gains:
    r_shoulder_pan_joint: {p: 800.0, d: 10.0}
    r_shoulder_lift_joint: {p: 800.0, d: 10.0}
    r_upper_arm_roll_joint: {p: 200.0, d: 3.0}
    r_elbow_flex_joint: {p: 100.0, d: 3.0}
    r_forearm_roll_joint: {p: 500.0, d: 6.0}
    r_wrist_flex_joint: {p: 400.0, d: 4.0}
    r_wrist_roll_joint: {p: 400.0, d: 4.0}
    l_shoulder_pan_joint: {p: 800.0, d: 10.0}
    l_shoulder_lift_joint: {p: 800.0, d: 10.0}
    l_upper_arm_roll_joint: {p: 200.0, d: 3.0}
    l_elbow_flex_joint: {p: 100.0, d: 3.0}
    l_forearm_roll_joint: {p: 500.0, d: 6.0}
    l_wrist_flex_joint: {p: 400.0, d: 4.0}
    l_wrist_roll_joint: {p: 400.0, d: 4.0}
  joint_trajectory_action_node:
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    constraints:
      goal_time: 0.6
      r_shoulder_pan_joint:
        goal: 0.02
      r_shoulder_lift_joint:
        goal: 0.02
      r_upper_arm_roll_joint:
        goal: 0.02
      r_elbow_flex_joint:
        goal: 0.02
      r_forearm_roll_joint:
        goal: 0.02
      r_wrist_flex_joint:
        goal: 0.02
      r_wrist_roll_joint:
        goal: 0.02
      l_shoulder_pan_joint:
        goal: 0.02
      l_shoulder_lift_joint:
        goal: 0.02
      l_upper_arm_roll_joint:
        goal: 0.02
      l_elbow_flex_joint:
        goal: 0.02
      l_forearm_roll_joint:
        goal: 0.02
      l_wrist_flex_joint:
        goal: 0.02
      l_wrist_roll_joint:
        goal: 0.02
