# The group the constraints operate on
string group

# The constraints for the space
Constraints constraints

# The size of the approximation (number of points)
int64 size

# The file where to save the space approximation
string filename
---

# Flag indicating whether the operation completed successfully 
bool success
