#!/usr/bin/env python
import sys
import rospy
from moveit_msgs.srv import LoadMap

filename = sys.argv[1]

rospy.init_node("load_map", anonymous=True)

load_map_service = rospy.ServiceProxy("move_group/load_map", LoadMap)
if load_map_service(filename):
    rospy.loginfo("Succeeded")
else:
    rospy.loginfo("Failed")
