# This service contains the definition for a request to the motion
# planner and the output it provides

MotionPlanRequest motion_plan_request

---

# A solution trajectory, if found
RobotTrajectory trajectory

# The corresponding robot state
RobotState trajectory_start

# Planning time
duration planning_time

# Error code - encodes the overall reason for failure
MoveItErrorCodes error_code
